# Generated by Django 5.2.15 on 2026-06-24 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newssource_country_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_content',
            field=models.TextField(blank=True, help_text='Full scraped body (from trafilatura)', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('auto_scraped', 'Auto Scraped'), ('enriched', 'Enriched'), ('editorial_reviewed', 'Editorial Reviewed'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='auto_scraped', max_length=50),
        ),
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bullet_points', models.JSONField(help_text='["point1", "point2", ...]')),
                ('sentiment', models.CharField(max_length=50)),
                ('sentiment_reason', models.TextField(blank=True, null=True)),
                ('key_entities', models.JSONField(help_text='{"people": [], "places": [], "orgs": []}')),
                ('reading_time_mins', models.IntegerField(default=1)),
                ('complexity', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_model', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='news.article')),
            ],
        ),
    ]
