# Generated by Django 5.2.15 on 2026-06-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_full_content_article_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Thumbnail image extracted from RSS feed', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='raw_content',
            field=models.TextField(help_text='Clean text scraped from the source (HTML stripped)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, max_length=2000, unique=True),
        ),
    ]
